<<<<<<< HEAD
# Basic Information
title: Minjia Li
=======
# Basic Information 
title: Minjia Li 
>>>>>>> feb273c2ab13f8dc2e0f698511ab936b0a2219bc
position: Assistant Professor of Accounting
affiliation: University of Alberta
affiliation_link: https://www.ualberta.ca/business/
affiliation_logo: assets/img/UA_Logo_Green_RGB.png
email: minjia4 (at) ualberta.ca

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Minjia Li, accounting, University of Alberta, disclosure, corporate governance, supply chain, political economy
description: Minjia Li is an Assistant Professor of Accounting at the University of Alberta, researching disclosure, corporate governance, and supply chain management.
canonical: https://minjia-li.github.io

# Links
# If you don't need one of them, you may delete the corresponding line.
link_type: icon
google_scholar: https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=3709935
cv_link: https://www.dropbox.com/scl/fi/q2gyg4uzpod70chospnxv/cv.pdf?rlkey=xv3kcts9vgwdbbblg9m6n3z95&st=biofnnah&dl=0
#github_link: https://github.com/
linkedin: https://linkedin.com/in/minjiali
#twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon)
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively.
avatar: ./assets/img/minjiali.jpeg
favicon: ./assets/img/favicon-32.png
favicon_dark: ./assets/img/favicon-32.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
